Add default exception handler
utopia-php/http pull request #54
Opened 2022-04-11 14:46 UTC by PineappleIOnic

This PR adds a default exception handler to utopia that is used when the user has not defined their own

2022-05-03 11:46 UTC, Meldiron approved these changes
LGTM

2022-05-03 12:00 UTC, eldadfux requested changes

2022-05-03 12:00 UTC, eldadfux commented on src/App.php
> +            if (self::$errors === ['*' => []]) { // If no error handler are set
Not 100% sure about this check, can we just check for `!empty(self::$errors['*'])`? We could also avoid the big `if` condition by just overwriting the empty array with our own callback and leave the default behavior as is.

2022-05-03 12:00 UTC, eldadfux commented on src/App.php
>              foreach ($groups as $group) {
Would also be great to add a test.

2022-05-06 21:36 UTC, christyjacob4 commented on src/App.php
> +                        \fwrite(STDERR, "Stacktrace: \n" . $error->getTraceAsString() . "\n");
Are there any side-effects of writing to a stream after using `response->send();`

Doesn't `response->send();` terminate the lifecycle of the request ?

2022-08-01 08:46 UTC, lohanidamodar commented on src/App.php
> +                self::$errors['*'][] = [
there is no longer `$errors['*']` please check the new implementation of errors.

2023-01-13 07:50 UTC, christyjacob4 commented
@PineappleIOnic please resolve the conflicts and check for the failing tests

2025-02-13 06:05 UTC, closed without merging